modified exceptions using Problem Details API
B1lok/TaskManager pull request #1
Opened 2023-09-04 15:35 UTC by B1lok

Edited the custom exceptions, now I don't need to write them to @ExceptionHandler

2023-09-04 15:36 UTC, B1lok commented
@Ekatereana

2023-09-05 13:07 UTC, Ekatereana requested changes
General recommendations:
- fixes branch -- in the pet projects it's not so crucial, but It's better to give the branches meanful names. This for example could be: problem-detail-fix
- for now the standard for the protected branch is not master, but rather main. It's not big deal, up to you
- I like your folder structure now looks much more cleaner and consistent 👍🏻 
- security folder --- I recommend rename the Config.java file. it  should be SecurityConfig at least, because when you will do search on name, it won't be obvious what config you are referring to.

2023-09-05 13:07 UTC, Ekatereana commented on src/main/java/com/example/taskmanager/exception/ForbiddenAccessException.java
> +    private static ProblemDetail asProblemDetail(String message){
buildProblemDetail, getPromblemDetail would be better in this context. according to [Oracle Java convention](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) the names of the methods should be verbs, it's popular and best practice contract so I recommend use it here also

2023-09-05 13:07 UTC, Ekatereana commented on src/main/java/com/example/taskmanager/exception/InvalidPasswordException.java
> +    private static ProblemDetail asProblemDetail(String message){
To avoid code duplication you may create the @UtilityClass -- this class would be static, it should be under the utils folder, you may put it on the exception folder or the upper level, please refer to Lombok docs https://projectlombok.org/features/experimental/UtilityClass

- good tutorial https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-09-05 13:07 UTC, Ekatereana commented on src/main/java/com/example/taskmanager/exception/UserAlreadyExistException.java
> +    private static ProblemDetail asProblemDetail(String message){
same, code duplication, see upper comments

2023-09-29 15:05 UTC, closed without merging